export const cantonmentData = [
  {
    _id: 1,
    cantonment_name: "Mirpur Cantonment",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 2,
    cantonment_name: "Savar Cantonment",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 3,
    cantonment_name: "Ekuria Cantonment",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 4,
    cantonment_name: "Bangladesh Military Academy",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 5,
    cantonment_name: "Chittagong Cantonment",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 6,
    cantonment_name: "Khagrachari Cantonment",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 7,
    cantonment_name: "Rangamati Cantonment",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 8,
    cantonment_name: "Bandarban Cantonment",
    district: "Bandarban",
    district_code: 3,
  },
  {
    _id: 9,
    cantonment_name: "Ishwardi Cantonment",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 10,
    cantonment_name: "Halishahar Cantonment",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 11,
    cantonment_name: "Kholahati Cantonment",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 12,
    cantonment_name: "Qadirabad Cantonment",
    district: "Natore",
    district_code: 69,
  },
  {
    _id: 13,
    cantonment_name: "Jessore Cantonment",
    district: "Jessore",
    district_code: 41,
  },
  {
    _id: 14,
    cantonment_name: "Jahanabad Cantonment",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 15,
    cantonment_name: "Rajshahi Cantonment",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 16,
    cantonment_name: "Jahingirabad Cantonment",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 17,
    cantonment_name: "Majhira Cantonment",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 18,
    cantonment_name: "Rangpur Cantontment",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 19,
    cantonment_name: "Saidpur Cantonment",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 20,
    cantonment_name: "Ghatail Cantonment",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 21,
    cantonment_name: "Chowkria Cantonment",
    district: "Cox's Bazar",
    district_code: 22,
  },
  {
    _id: 22,
    cantonment_name: "Rajendrapur Cantonment",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 23,
    cantonment_name: "Mymensingh Cantonment",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 24,
    cantonment_name: "Jalalabad Cantonment",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 25,
    cantonment_name: "Mainamati Cantonment",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 26,
    cantonment_name: "Zamuna Satu Cantonment",
    district: "Tangail",
    district_code: 93,
  },
];
