export const thanaData = [
  {
    _id: 1,
    thana_name: "Bamna",
    district: "Barguna",
    district_code: 4,
  },
  {
    _id: 2,
    thana_name: "Barguna Sadar",
    district: "Barguna",
    district_code: 4,
  },
  {
    _id: 3,
    thana_name: "Betagi",
    district: "Barguna",
    district_code: 4,
  },
  {
    _id: 4,
    thana_name: "Patharghata",
    district: "Barguna",
    district_code: 4,
  },
  {
    _id: 5,
    thana_name: "Amtali",
    district: "Barguna",
    district_code: 4,
  },
  {
    _id: 6,
    thana_name: "Taltali",
    district: "Barguna",
    district_code: 4,
  },
  {
    _id: 7,
    thana_name: "Jhalokati Sadar",
    district: "Jhalokati",
    district_code: 42,
  },
  {
    _id: 8,
    thana_name: "Kanthalia",
    district: "Jhalokati",
    district_code: 42,
  },
  {
    _id: 9,
    thana_name: "Nalchity",
    district: "Jhalokati",
    district_code: 42,
  },
  {
    _id: 10,
    thana_name: "Rajapur",
    district: "Jhalokati",
    district_code: 42,
  },
  {
    _id: 11,
    thana_name: "Kotwali (S)",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 12,
    thana_name: "Airport",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 13,
    thana_name: "Kawnia",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 14,
    thana_name: "Bandar",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 15,
    thana_name: "Rupatali",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 16,
    thana_name: "University",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 17,
    thana_name: "Char Monai",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 18,
    thana_name: "Kashipur",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 19,
    thana_name: "Banari Para",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 20,
    thana_name: "Agailjhara",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 21,
    thana_name: "Babuganj",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 22,
    thana_name: "Gaurnadi",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 23,
    thana_name: "Hizla",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 24,
    thana_name: "Mhendiganj",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 25,
    thana_name: "Muladi",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 26,
    thana_name: "Bakerganj",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 27,
    thana_name: "Wazirpur",
    district: "Barisal",
    district_code: 6,
  },
  {
    _id: 28,
    thana_name: "Bauphal",
    district: "Patuakhali",
    district_code: 78,
  },
  {
    _id: 29,
    thana_name: "Dashmina",
    district: "Patuakhali",
    district_code: 78,
  },
  {
    _id: 30,
    thana_name: "Dumki",
    district: "Patuakhali",
    district_code: 78,
  },
  {
    _id: 31,
    thana_name: "Galachipa",
    district: "Patuakhali",
    district_code: 78,
  },
  {
    _id: 32,
    thana_name: "Kalapara",
    district: "Patuakhali",
    district_code: 78,
  },
  {
    _id: 33,
    thana_name: "Mirzaganj",
    district: "Patuakhali",
    district_code: 78,
  },
  {
    _id: 34,
    thana_name: "Patuakhali Sadar",
    district: "Patuakhali",
    district_code: 78,
  },
  {
    _id: 35,
    thana_name: "Rangabali",
    district: "Patuakhali",
    district_code: 78,
  },
  {
    _id: 36,
    thana_name: "Bhandaria",
    district: "Pirojpur",
    district_code: 79,
  },
  {
    _id: 37,
    thana_name: "Kawkhali",
    district: "Pirojpur",
    district_code: 79,
  },
  {
    _id: 38,
    thana_name: "Mathbaria",
    district: "Pirojpur",
    district_code: 79,
  },
  {
    _id: 39,
    thana_name: "Nazirpur",
    district: "Pirojpur",
    district_code: 79,
  },
  {
    _id: 40,
    thana_name: "Pirojpur Sadar",
    district: "Pirojpur",
    district_code: 79,
  },
  {
    _id: 41,
    thana_name: "Nesarabad (Swarupkati)",
    district: "Pirojpur",
    district_code: 79,
  },
  {
    _id: 42,
    thana_name: "Zianagar",
    district: "Pirojpur",
    district_code: 79,
  },
  {
    _id: 43,
    thana_name: "Bhola Sadar",
    district: "Bhola",
    district_code: 9,
  },
  {
    _id: 44,
    thana_name: "Burhanuddin",
    district: "Bhola",
    district_code: 9,
  },
  {
    _id: 45,
    thana_name: "Char Fasson",
    district: "Bhola",
    district_code: 9,
  },
  {
    _id: 46,
    thana_name: "Daulat Khan",
    district: "Bhola",
    district_code: 9,
  },
  {
    _id: 47,
    thana_name: "Lalmohan",
    district: "Bhola",
    district_code: 9,
  },
  {
    _id: 48,
    thana_name: "Manpura",
    district: "Bhola",
    district_code: 9,
  },
  {
    _id: 49,
    thana_name: "Tazumuddin",
    district: "Bhola",
    district_code: 9,
  },
  {
    _id: 50,
    thana_name: "Brahmanbaria Sadar",
    district: "Brahmanbaria",
    district_code: 12,
  },
  {
    _id: 51,
    thana_name: "Akhaura",
    district: "Brahmanbaria",
    district_code: 12,
  },
  {
    _id: 52,
    thana_name: "Ashuganj",
    district: "Brahmanbaria",
    district_code: 12,
  },
  {
    _id: 53,
    thana_name: "Banchharampur",
    district: "Brahmanbaria",
    district_code: 12,
  },
  {
    _id: 54,
    thana_name: "Kasba",
    district: "Brahmanbaria",
    district_code: 12,
  },
  {
    _id: 55,
    thana_name: "Bijoynagar",
    district: "Brahmanbaria",
    district_code: 12,
  },
  {
    _id: 56,
    thana_name: "Nabinagar",
    district: "Brahmanbaria",
    district_code: 12,
  },
  {
    _id: 57,
    thana_name: "Nasirnagar",
    district: "Brahmanbaria",
    district_code: 12,
  },
  {
    _id: 58,
    thana_name: "Sarail",
    district: "Brahmanbaria",
    district_code: 12,
  },
  {
    _id: 59,
    thana_name: "Chandpur Sadar",
    district: "Chandpur",
    district_code: 13,
  },
  {
    _id: 60,
    thana_name: "Faridganj",
    district: "Chandpur",
    district_code: 13,
  },
  {
    _id: 61,
    thana_name: "Haim Char",
    district: "Chandpur",
    district_code: 13,
  },
  {
    _id: 62,
    thana_name: "Hajiganj",
    district: "Chandpur",
    district_code: 13,
  },
  {
    _id: 63,
    thana_name: "Kachua",
    district: "Chandpur",
    district_code: 13,
  },
  {
    _id: 64,
    thana_name: "Matlab Dakshin",
    district: "Chandpur",
    district_code: 13,
  },
  {
    _id: 65,
    thana_name: "Matlab Uttar",
    district: "Chandpur",
    district_code: 13,
  },
  {
    _id: 66,
    thana_name: "Shahrasti",
    district: "Chandpur",
    district_code: 13,
  },
  {
    _id: 67,
    thana_name: "Chittagong Kotwali",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 68,
    thana_name: "Chandgaon",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 69,
    thana_name: "Halishahar",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 70,
    thana_name: "Khulshi",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 71,
    thana_name: "Karnafuli",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 72,
    thana_name: "Pahartali",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 73,
    thana_name: "Panchlaish",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 74,
    thana_name: "Bayejid Bostami",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 75,
    thana_name: "Patenga",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 76,
    thana_name: "Akbar Shah",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 77,
    thana_name: "Chawk Bazar",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 78,
    thana_name: "Bakalia",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 79,
    thana_name: "Sadarghat",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 80,
    thana_name: "Double Mooring",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 81,
    thana_name: "EPZ",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 82,
    thana_name: "Bandar",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 83,
    thana_name: "Lohagara",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 84,
    thana_name: "Boalkhali",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 85,
    thana_name: "Chandanaish",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 86,
    thana_name: "Fatikchhari",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 87,
    thana_name: "Vujpur",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 88,
    thana_name: "Hathazari",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 89,
    thana_name: "Anowara",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 90,
    thana_name: "Mirsharai",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 91,
    thana_name: "Jorarganj",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 92,
    thana_name: "Patiya",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 93,
    thana_name: "Rangunia",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 94,
    thana_name: "Raozan",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 95,
    thana_name: "Sandwip",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 96,
    thana_name: "Banshkhali",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 97,
    thana_name: "Satkania",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 98,
    thana_name: "Sitakunda",
    district: "Chittagong",
    district_code: 15,
  },
  {
    _id: 99,
    thana_name: "Lalmai",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 100,
    thana_name: "Brahman Para",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 101,
    thana_name: "Burichang",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 102,
    thana_name: "Chandina",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 103,
    thana_name: "Chauddagram",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 104,
    thana_name: "Sadar (South)",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 105,
    thana_name: "Daudkandi",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 106,
    thana_name: "Debidwar",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 107,
    thana_name: "Homna",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 108,
    thana_name: "Sadar",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 109,
    thana_name: "Laksam",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 110,
    thana_name: "Manoharganj",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 111,
    thana_name: "Meghna",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 112,
    thana_name: "Muradnagar",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 113,
    thana_name: "Bangara Bazar",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 114,
    thana_name: "Nangalkot",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 115,
    thana_name: "Barura",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 116,
    thana_name: "Titas",
    district: "Comilla",
    district_code: 19,
  },
  {
    _id: 117,
    thana_name: "Chakaria",
    district: "Cox'S Bazar",
    district_code: 22,
  },
  {
    _id: 118,
    thana_name: "Cox'S Bazar Sadar",
    district: "Cox'S Bazar",
    district_code: 22,
  },
  {
    _id: 119,
    thana_name: "Kutubdia",
    district: "Cox'S Bazar",
    district_code: 22,
  },
  {
    _id: 120,
    thana_name: "Maheshkhali",
    district: "Cox'S Bazar",
    district_code: 22,
  },
  {
    _id: 121,
    thana_name: "Pekua",
    district: "Cox'S Bazar",
    district_code: 22,
  },
  {
    _id: 122,
    thana_name: "Ramu",
    district: "Cox'S Bazar",
    district_code: 22,
  },
  {
    _id: 123,
    thana_name: "Teknaf",
    district: "Cox'S Bazar",
    district_code: 22,
  },
  {
    _id: 124,
    thana_name: "Ukhia",
    district: "Cox'S Bazar",
    district_code: 22,
  },
  {
    _id: 125,
    thana_name: "Bandarban Sadar",
    district: "Bandarban",
    district_code: 3,
  },
  {
    _id: 126,
    thana_name: "Alikadam",
    district: "Bandarban",
    district_code: 3,
  },
  {
    _id: 127,
    thana_name: "Lama",
    district: "Bandarban",
    district_code: 3,
  },
  {
    _id: 128,
    thana_name: "Naikhongchhari",
    district: "Bandarban",
    district_code: 3,
  },
  {
    _id: 129,
    thana_name: "Rowangchhari",
    district: "Bandarban",
    district_code: 3,
  },
  {
    _id: 130,
    thana_name: "Ruma",
    district: "Bandarban",
    district_code: 3,
  },
  {
    _id: 131,
    thana_name: "Thanchi",
    district: "Bandarban",
    district_code: 3,
  },
  {
    _id: 132,
    thana_name: "Chhagalnaiya",
    district: "Feni",
    district_code: 30,
  },
  {
    _id: 133,
    thana_name: "Daganbhuiyan",
    district: "Feni",
    district_code: 30,
  },
  {
    _id: 134,
    thana_name: "Feni Sadar",
    district: "Feni",
    district_code: 30,
  },
  {
    _id: 135,
    thana_name: "Fulgazi",
    district: "Feni",
    district_code: 30,
  },
  {
    _id: 136,
    thana_name: "Parshuram",
    district: "Feni",
    district_code: 30,
  },
  {
    _id: 137,
    thana_name: "Sonagazi",
    district: "Feni",
    district_code: 30,
  },
  {
    _id: 138,
    thana_name: "Khagrachhari Sadar",
    district: "Khagrachhari",
    district_code: 46,
  },
  {
    _id: 139,
    thana_name: "Dighinala",
    district: "Khagrachhari",
    district_code: 46,
  },
  {
    _id: 140,
    thana_name: "Laxmichhari",
    district: "Khagrachhari",
    district_code: 46,
  },
  {
    _id: 141,
    thana_name: "Mahalchhari",
    district: "Khagrachhari",
    district_code: 46,
  },
  {
    _id: 142,
    thana_name: "Manikchhari",
    district: "Khagrachhari",
    district_code: 46,
  },
  {
    _id: 143,
    thana_name: "Matiranga",
    district: "Khagrachhari",
    district_code: 46,
  },
  {
    _id: 144,
    thana_name: "Panchhari",
    district: "Khagrachhari",
    district_code: 46,
  },
  {
    _id: 145,
    thana_name: "Ramgarh",
    district: "Khagrachhari",
    district_code: 46,
  },
  {
    _id: 146,
    thana_name: "Guimara",
    district: "Khagrachhari",
    district_code: 46,
  },
  {
    _id: 147,
    thana_name: "Kamalnagar",
    district: "Lakshmipur",
    district_code: 51,
  },
  {
    _id: 148,
    thana_name: "Lakshmipur Sadar",
    district: "Lakshmipur",
    district_code: 51,
  },
  {
    _id: 149,
    thana_name: "Raipur",
    district: "Lakshmipur",
    district_code: 51,
  },
  {
    _id: 150,
    thana_name: "Ramganj",
    district: "Lakshmipur",
    district_code: 51,
  },
  {
    _id: 151,
    thana_name: "Ramgati",
    district: "Lakshmipur",
    district_code: 51,
  },
  {
    _id: 152,
    thana_name: "Chatkhil",
    district: "Noakhali",
    district_code: 75,
  },
  {
    _id: 153,
    thana_name: "Companiganj",
    district: "Noakhali",
    district_code: 75,
  },
  {
    _id: 154,
    thana_name: "Hatiya",
    district: "Noakhali",
    district_code: 75,
  },
  {
    _id: 155,
    thana_name: "Kabirhat",
    district: "Noakhali",
    district_code: 75,
  },
  {
    _id: 156,
    thana_name: "Begumganj",
    district: "Noakhali",
    district_code: 75,
  },
  {
    _id: 157,
    thana_name: "Senbagh",
    district: "Noakhali",
    district_code: 75,
  },
  {
    _id: 158,
    thana_name: "Sonaimuri",
    district: "Noakhali",
    district_code: 75,
  },
  {
    _id: 159,
    thana_name: "Subarnachar",
    district: "Noakhali",
    district_code: 75,
  },
  {
    _id: 160,
    thana_name: "Noakhali Sadar",
    district: "Noakhali",
    district_code: 75,
  },
  {
    _id: 161,
    thana_name: "Barkal",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 162,
    thana_name: "Kawkhali (Betbunia)",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 163,
    thana_name: "Bilai Chhari",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 164,
    thana_name: "Kaptai",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 165,
    thana_name: "JuraiChhari",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 166,
    thana_name: "Langadu",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 167,
    thana_name: "Baghaichhari",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 168,
    thana_name: "Naniarchar",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 169,
    thana_name: "Rajasthali",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 170,
    thana_name: "Rangamati Sadar",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 171,
    thana_name: "Chandroghona",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 172,
    thana_name: "Sazek",
    district: "Rangamati",
    district_code: 84,
  },
  {
    _id: 173,
    thana_name: "Dakshinkhan",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 174,
    thana_name: "Darus Salam",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 175,
    thana_name: "Demra",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 176,
    thana_name: "Dhanmondi",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 177,
    thana_name: "Adabor",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 178,
    thana_name: "Bhasan Tek",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 179,
    thana_name: "Bhatara",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 180,
    thana_name: "Gendaria",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 181,
    thana_name: "Gulshan",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 182,
    thana_name: "Hatirjheel",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 183,
    thana_name: "Hazaribagh",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 184,
    thana_name: "Jatrabari",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 185,
    thana_name: "Kafrul",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 186,
    thana_name: "Kadamtali",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 187,
    thana_name: "Kalabagan",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 188,
    thana_name: "Kamrangir Char",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 189,
    thana_name: "Khilgaon",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 190,
    thana_name: "Khilkhet",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 191,
    thana_name: "Badda",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 192,
    thana_name: "Kotwali",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 193,
    thana_name: "Lalbagh",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 194,
    thana_name: "Mirpur",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 195,
    thana_name: "Bangshal",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 196,
    thana_name: "Mohammadpur",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 197,
    thana_name: "Motijheel",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 198,
    thana_name: "Mugda Para",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 199,
    thana_name: "Biman Bandar",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 200,
    thana_name: "New Market",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 201,
    thana_name: "Pallabi",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 202,
    thana_name: "Paltan",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 203,
    thana_name: "Ramna",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 204,
    thana_name: "Rampura",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 205,
    thana_name: "Sabujbagh",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 206,
    thana_name: "Banani",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 207,
    thana_name: "Rupnagar",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 208,
    thana_name: "Shahjahanpur",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 209,
    thana_name: "Shah Ali",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 210,
    thana_name: "Shahbagh",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 211,
    thana_name: "Shyampur",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 212,
    thana_name: "Cantonment",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 213,
    thana_name: "Sher-E-Bangla Nagar",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 214,
    thana_name: "Sutrapur",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 215,
    thana_name: "Chak Bazar",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 216,
    thana_name: "Tejgaon",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 217,
    thana_name: "Tejgaon Ind. Area",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 218,
    thana_name: "Turag",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 219,
    thana_name: "Uttara Paschim",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 220,
    thana_name: "Uttara Purba",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 221,
    thana_name: "Uttar Khan",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 222,
    thana_name: "Wari",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 223,
    thana_name: "Dhamrai",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 224,
    thana_name: "Dohar",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 225,
    thana_name: "Keraniganj",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 226,
    thana_name: "Nawabganj",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 227,
    thana_name: "Savar",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 228,
    thana_name: "Ashulia",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 229,
    thana_name: "Keraniganj (South)",
    district: "Dhaka",
    district_code: 26,
  },
  {
    _id: 230,
    thana_name: "Bhanga",
    district: "Faridpur",
    district_code: 29,
  },
  {
    _id: 231,
    thana_name: "Boalmari",
    district: "Faridpur",
    district_code: 29,
  },
  {
    _id: 232,
    thana_name: "Char Bhadrasan",
    district: "Faridpur",
    district_code: 29,
  },
  {
    _id: 233,
    thana_name: "Alfadanga",
    district: "Faridpur",
    district_code: 29,
  },
  {
    _id: 234,
    thana_name: "Faridpur Sadar",
    district: "Faridpur",
    district_code: 29,
  },
  {
    _id: 235,
    thana_name: "Madhukhali",
    district: "Faridpur",
    district_code: 29,
  },
  {
    _id: 236,
    thana_name: "Nagarkanda",
    district: "Faridpur",
    district_code: 29,
  },
  {
    _id: 237,
    thana_name: "Sadarpur",
    district: "Faridpur",
    district_code: 29,
  },
  {
    _id: 238,
    thana_name: "Saltha",
    district: "Faridpur",
    district_code: 29,
  },
  {
    _id: 239,
    thana_name: "Gazipur (Sadar)",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 240,
    thana_name: "Gacha",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 241,
    thana_name: "Tongi (North)",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 242,
    thana_name: "Tongi (West)",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 243,
    thana_name: "Konabari",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 244,
    thana_name: "Kashimpur",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 245,
    thana_name: "Pubail",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 246,
    thana_name: "Bason",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 247,
    thana_name: "Kaliakair",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 248,
    thana_name: "Kaliganj",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 249,
    thana_name: "Kapasia",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 250,
    thana_name: "Sreepur",
    district: "Gazipur",
    district_code: 33,
  },
  {
    _id: 251,
    thana_name: "Gopalganj Sadar",
    district: "Gopalganj",
    district_code: 35,
  },
  {
    _id: 252,
    thana_name: "Kashiani",
    district: "Gopalganj",
    district_code: 35,
  },
  {
    _id: 253,
    thana_name: "Kotalipara",
    district: "Gopalganj",
    district_code: 35,
  },
  {
    _id: 254,
    thana_name: "Muksudpur",
    district: "Gopalganj",
    district_code: 35,
  },
  {
    _id: 255,
    thana_name: "Tungipara",
    district: "Gopalganj",
    district_code: 35,
  },
  {
    _id: 256,
    thana_name: "Bhairab",
    district: "Kishoregonj",
  },
  {
    _id: 257,
    thana_name: "Austagram",
    district: "Kishoregonj",
  },
  {
    _id: 258,
    thana_name: "Hossainpur",
    district: "Kishoregonj",
  },
  {
    _id: 259,
    thana_name: "Itna",
    district: "Kishoregonj",
  },
  {
    _id: 260,
    thana_name: "Karimganj",
    district: "Kishoregonj",
  },
  {
    _id: 261,
    thana_name: "Katiadi",
    district: "Kishoregonj",
  },
  {
    _id: 262,
    thana_name: "Kishoreganj Sadar",
    district: "Kishoregonj",
  },
  {
    _id: 263,
    thana_name: "Kuliar Char",
    district: "Kishoregonj",
  },
  {
    _id: 264,
    thana_name: "Mithamain",
    district: "Kishoregonj",
  },
  {
    _id: 265,
    thana_name: "Bajitpur",
    district: "Kishoregonj",
  },
  {
    _id: 266,
    thana_name: "Nikli",
    district: "Kishoregonj",
  },
  {
    _id: 267,
    thana_name: "Pakundia",
    district: "Kishoregonj",
  },
  {
    _id: 268,
    thana_name: "Tarail",
    district: "Kishoregonj",
  },
  {
    _id: 269,
    thana_name: "Kalkini",
    district: "Madaripur",
    district_code: 54,
  },
  {
    _id: 270,
    thana_name: "Madaripur Sadar",
    district: "Madaripur",
    district_code: 54,
  },
  {
    _id: 271,
    thana_name: "Rajoir",
    district: "Madaripur",
    district_code: 54,
  },
  {
    _id: 272,
    thana_name: "Shibchar",
    district: "Madaripur",
    district_code: 54,
  },
  {
    _id: 273,
    thana_name: "Chashar",
    district: "Madaripur",
    district_code: 54,
  },
  {
    _id: 274,
    thana_name: "Daulatpur",
    district: "Manikganj",
    district_code: 56,
  },
  {
    _id: 275,
    thana_name: "Ghior",
    district: "Manikganj",
    district_code: 56,
  },
  {
    _id: 276,
    thana_name: "Harirampur",
    district: "Manikganj",
    district_code: 56,
  },
  {
    _id: 277,
    thana_name: "Manikganj Sadar",
    district: "Manikganj",
    district_code: 56,
  },
  {
    _id: 278,
    thana_name: "Saturia",
    district: "Manikganj",
    district_code: 56,
  },
  {
    _id: 279,
    thana_name: "Shibalaya",
    district: "Manikganj",
    district_code: 56,
  },
  {
    _id: 280,
    thana_name: "Singair",
    district: "Manikganj",
    district_code: 56,
  },
  {
    _id: 281,
    thana_name: "Gazaria",
    district: "Munshiganj",
    district_code: 59,
  },
  {
    _id: 282,
    thana_name: "Lohajang",
    district: "Munshiganj",
    district_code: 59,
  },
  {
    _id: 283,
    thana_name: "Munshiganj Sadar",
    district: "Munshiganj",
    district_code: 59,
  },
  {
    _id: 284,
    thana_name: "Serajdikhan",
    district: "Munshiganj",
    district_code: 59,
  },
  {
    _id: 285,
    thana_name: "Sreenagar",
    district: "Munshiganj",
    district_code: 59,
  },
  {
    _id: 286,
    thana_name: "Tongibari",
    district: "Munshiganj",
    district_code: 59,
  },
  {
    _id: 287,
    thana_name: "Narayanganj Sadar",
    district: "Narayanganj",
    district_code: 67,
  },
  {
    _id: 288,
    thana_name: "Fotullah",
    district: "Narayanganj",
    district_code: 67,
  },
  {
    _id: 289,
    thana_name: "Siddhirganj",
    district: "Narayanganj",
    district_code: 67,
  },
  {
    _id: 290,
    thana_name: "Araihazar",
    district: "Narayanganj",
    district_code: 67,
  },
  {
    _id: 291,
    thana_name: "Sonargaon",
    district: "Narayanganj",
    district_code: 67,
  },
  {
    _id: 292,
    thana_name: "Bandar",
    district: "Narayanganj",
    district_code: 67,
  },
  {
    _id: 293,
    thana_name: "Rupganj",
    district: "Narayanganj",
    district_code: 67,
  },
  {
    _id: 294,
    thana_name: "Manohardi",
    district: "Narsingdi",
    district_code: 68,
  },
  {
    _id: 295,
    thana_name: "Narsingdi Sadar",
    district: "Narsingdi",
    district_code: 68,
  },
  {
    _id: 296,
    thana_name: "Palash",
    district: "Narsingdi",
    district_code: 68,
  },
  {
    _id: 297,
    thana_name: "Roypura",
    district: "Narsingdi",
    district_code: 68,
  },
  {
    _id: 298,
    thana_name: "Belabo",
    district: "Narsingdi",
    district_code: 68,
  },
  {
    _id: 299,
    thana_name: "Shibpur",
    district: "Narsingdi",
    district_code: 68,
  },
  {
    _id: 300,
    thana_name: "Goalanda",
    district: "Rajbari",
    district_code: 82,
  },
  {
    _id: 301,
    thana_name: "Kalukhali",
    district: "Rajbari",
    district_code: 82,
  },
  {
    _id: 302,
    thana_name: "Baliakandi",
    district: "Rajbari",
    district_code: 82,
  },
  {
    _id: 303,
    thana_name: "Pangsha",
    district: "Rajbari",
    district_code: 82,
  },
  {
    _id: 304,
    thana_name: "Rajbari Sadar",
    district: "Rajbari",
    district_code: 82,
  },
  {
    _id: 305,
    thana_name: "Shariatpur Sadar",
    district: "Shariatpur",
    district_code: 86,
  },
  {
    _id: 306,
    thana_name: "Bhedarganj",
    district: "Shariatpur",
    district_code: 86,
  },
  {
    _id: 307,
    thana_name: "Damudya",
    district: "Shariatpur",
    district_code: 86,
  },
  {
    _id: 308,
    thana_name: "Gosairhat",
    district: "Shariatpur",
    district_code: 86,
  },
  {
    _id: 309,
    thana_name: "Naria",
    district: "Shariatpur",
    district_code: 86,
  },
  {
    _id: 310,
    thana_name: "Zanjira",
    district: "Shariatpur",
    district_code: 86,
  },
  {
    _id: 311,
    thana_name: "Palong",
    district: "Shariatpur",
    district_code: 86,
  },
  {
    _id: 312,
    thana_name: "Tangail Sadar",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 313,
    thana_name: "Bhuapur",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 314,
    thana_name: "Delduar",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 315,
    thana_name: "Dhanbari",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 316,
    thana_name: "Ghatail",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 317,
    thana_name: "Gopalpur",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 318,
    thana_name: "Kalihati",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 319,
    thana_name: "Madhupur",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 320,
    thana_name: "Mirzapur",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 321,
    thana_name: "Nagarpur",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 322,
    thana_name: "Sakhipur",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 323,
    thana_name: "Basail",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 324,
    thana_name: "BB. Bridge (East)",
    district: "Tangail",
    district_code: 93,
  },
  {
    _id: 325,
    thana_name: "Chitalmari",
    district: "Bagerhat",
    district_code: 1,
  },
  {
    _id: 326,
    thana_name: "Fakirhat",
    district: "Bagerhat",
    district_code: 1,
  },
  {
    _id: 327,
    thana_name: "Kachua",
    district: "Bagerhat",
    district_code: 1,
  },
  {
    _id: 328,
    thana_name: "Mollahat",
    district: "Bagerhat",
    district_code: 1,
  },
  {
    _id: 329,
    thana_name: "Mongla",
    district: "Bagerhat",
    district_code: 1,
  },
  {
    _id: 330,
    thana_name: "Morrelganj",
    district: "Bagerhat",
    district_code: 1,
  },
  {
    _id: 331,
    thana_name: "Rampal",
    district: "Bagerhat",
    district_code: 1,
  },
  {
    _id: 332,
    thana_name: "Sarankhola",
    district: "Bagerhat",
    district_code: 1,
  },
  {
    _id: 333,
    thana_name: "Bagerhat Sadar",
    district: "Bagerhat",
    district_code: 1,
  },
  {
    _id: 334,
    thana_name: "Chuadanga Sadar",
    district: "Chuadanga",
    district_code: 18,
  },
  {
    _id: 335,
    thana_name: "Damurhuda",
    district: "Chuadanga",
    district_code: 18,
  },
  {
    _id: 336,
    thana_name: "Jiban Nagar",
    district: "Chuadanga",
    district_code: 18,
  },
  {
    _id: 337,
    thana_name: "Alamdanga",
    district: "Chuadanga",
    district_code: 18,
  },
  {
    _id: 338,
    thana_name: "Chaugachha",
    district: "Jessore",
    district_code: 41,
  },
  {
    _id: 339,
    thana_name: "Jhikargachha",
    district: "Jessore",
    district_code: 41,
  },
  {
    _id: 340,
    thana_name: "Keshabpur",
    district: "Jessore",
    district_code: 41,
  },
  {
    _id: 341,
    thana_name: "Abhaynagar",
    district: "Jessore",
    district_code: 41,
  },
  {
    _id: 342,
    thana_name: "Jessore Sadar",
    district: "Jessore",
    district_code: 41,
  },
  {
    _id: 343,
    thana_name: "Manirampur",
    district: "Jessore",
    district_code: 41,
  },
  {
    _id: 344,
    thana_name: "Bagher Para",
    district: "Jessore",
    district_code: 41,
  },
  {
    _id: 345,
    thana_name: "Sharsha",
    district: "Jessore",
    district_code: 41,
  },
  {
    _id: 346,
    thana_name: "Harinakunda",
    district: "Jhenaidah",
    district_code: 44,
  },
  {
    _id: 347,
    thana_name: "Jhenaidah Sadar",
    district: "Jhenaidah",
    district_code: 44,
  },
  {
    _id: 348,
    thana_name: "Kaliganj",
    district: "Jhenaidah",
    district_code: 44,
  },
  {
    _id: 349,
    thana_name: "Kotchandpur",
    district: "Jhenaidah",
    district_code: 44,
  },
  {
    _id: 350,
    thana_name: "Maheshpur",
    district: "Jhenaidah",
    district_code: 44,
  },
  {
    _id: 351,
    thana_name: "Shailkupa",
    district: "Jhenaidah",
    district_code: 44,
  },
  {
    _id: 352,
    thana_name: "Khulna (Sadar)",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 353,
    thana_name: "Labanchara",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 354,
    thana_name: "Harintana",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 355,
    thana_name: "Aranghata",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 356,
    thana_name: "Daulatpur",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 357,
    thana_name: "Khalishpur",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 358,
    thana_name: "Khan Jahan Ali",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 359,
    thana_name: "Sonadanga",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 360,
    thana_name: "Batiaghata",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 361,
    thana_name: "Dacope",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 362,
    thana_name: "Dumuria",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 363,
    thana_name: "Dighalia",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 364,
    thana_name: "Koyra",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 365,
    thana_name: "Paikgachha",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 366,
    thana_name: "Phultala",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 367,
    thana_name: "Rupsa",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 368,
    thana_name: "Terokhada",
    district: "Khulna",
    district_code: 47,
  },
  {
    _id: 369,
    thana_name: "Bheramara",
    district: "Kushtia",
    district_code: 50,
  },
  {
    _id: 370,
    thana_name: "Daulatpur",
    district: "Kushtia",
    district_code: 50,
  },
  {
    _id: 371,
    thana_name: "Khoksa",
    district: "Kushtia",
    district_code: 50,
  },
  {
    _id: 372,
    thana_name: "Kumarkhali",
    district: "Kushtia",
    district_code: 50,
  },
  {
    _id: 373,
    thana_name: "Kushtia Sadar",
    district: "Kushtia",
    district_code: 50,
  },
  {
    _id: 374,
    thana_name: "Mirpur",
    district: "Kushtia",
    district_code: 50,
  },
  {
    _id: 375,
    thana_name: "Magura Sadar",
    district: "Magura",
    district_code: 55,
  },
  {
    _id: 376,
    thana_name: "Mohammadpur",
    district: "Magura",
    district_code: 55,
  },
  {
    _id: 377,
    thana_name: "Shalikha",
    district: "Magura",
    district_code: 55,
  },
  {
    _id: 378,
    thana_name: "Sreepur",
    district: "Magura",
    district_code: 55,
  },
  {
    _id: 379,
    thana_name: "Gangni",
    district: "Meherpur",
    district_code: 57,
  },
  {
    _id: 380,
    thana_name: "Mujib Nagar",
    district: "Meherpur",
    district_code: 57,
  },
  {
    _id: 381,
    thana_name: "Meherpur Sadar",
    district: "Meherpur",
    district_code: 57,
  },
  {
    _id: 382,
    thana_name: "Kalia",
    district: "Narail",
    district_code: 65,
  },
  {
    _id: 383,
    thana_name: "Lohagara",
    district: "Narail",
    district_code: 65,
  },
  {
    _id: 384,
    thana_name: "Narail Sadar",
    district: "Narail",
    district_code: 65,
  },
  {
    _id: 385,
    thana_name: "Debhata",
    district: "Satkhira",
    district_code: 87,
  },
  {
    _id: 386,
    thana_name: "Assasuni",
    district: "Satkhira",
    district_code: 87,
  },
  {
    _id: 387,
    thana_name: "Kalaroa",
    district: "Satkhira",
    district_code: 87,
  },
  {
    _id: 388,
    thana_name: "Kaliganj",
    district: "Satkhira",
    district_code: 87,
  },
  {
    _id: 389,
    thana_name: "Satkhira Sadar",
    district: "Satkhira",
    district_code: 87,
  },
  {
    _id: 390,
    thana_name: "Shyamnagar",
    district: "Satkhira",
    district_code: 87,
  },
  {
    _id: 391,
    thana_name: "Tala",
    district: "Satkhira",
    district_code: 87,
  },
  {
    _id: 392,
    thana_name: "Dewanganj",
    district: "Jamalpur",
    district_code: 39,
  },
  {
    _id: 393,
    thana_name: "Islampur",
    district: "Jamalpur",
    district_code: 39,
  },
  {
    _id: 394,
    thana_name: "Jamalpur Sadar",
    district: "Jamalpur",
    district_code: 39,
  },
  {
    _id: 395,
    thana_name: "Madarganj",
    district: "Jamalpur",
    district_code: 39,
  },
  {
    _id: 396,
    thana_name: "Melandaha",
    district: "Jamalpur",
    district_code: 39,
  },
  {
    _id: 397,
    thana_name: "Bakshiganj",
    district: "Jamalpur",
    district_code: 39,
  },
  {
    _id: 398,
    thana_name: "Sarishabari Upazila",
    district: "Jamalpur",
    district_code: 39,
  },
  {
    _id: 399,
    thana_name: "Bhaluka",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 400,
    thana_name: "Dhobaura",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 401,
    thana_name: "Fulbaria",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 402,
    thana_name: "Gaforgaon",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 403,
    thana_name: "Gouripur",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 404,
    thana_name: "Haluaghat",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 405,
    thana_name: "Ishwarganj",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 406,
    thana_name: "Mymensingh Sadar",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 407,
    thana_name: "Muktagachha",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 408,
    thana_name: "Nandail",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 409,
    thana_name: "Phulpur",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 410,
    thana_name: "Trishal",
    district: "Mymensingh",
    district_code: 61,
  },
  {
    _id: 411,
    thana_name: "Durgapur",
    district: "Netrakona",
    district_code: 72,
  },
  {
    _id: 412,
    thana_name: "Khaliajuri",
    district: "Netrakona",
    district_code: 72,
  },
  {
    _id: 413,
    thana_name: "Atpara",
    district: "Netrakona",
    district_code: 72,
  },
  {
    _id: 414,
    thana_name: "Kalmakanda",
    district: "Netrakona",
    district_code: 72,
  },
  {
    _id: 415,
    thana_name: "Kendua",
    district: "Netrakona",
    district_code: 72,
  },
  {
    _id: 416,
    thana_name: "Madan",
    district: "Netrakona",
    district_code: 72,
  },
  {
    _id: 417,
    thana_name: "Mohanganj",
    district: "Netrakona",
    district_code: 72,
  },
  {
    _id: 418,
    thana_name: "Netrokona Sadar",
    district: "Netrakona",
    district_code: 72,
  },
  {
    _id: 419,
    thana_name: "Purbadhala",
    district: "Netrakona",
    district_code: 72,
  },
  {
    _id: 420,
    thana_name: "Barhatta",
    district: "Netrakona",
    district_code: 72,
  },
  {
    _id: 421,
    thana_name: "Jhenaigati",
    district: "Sherpur",
    district_code: 89,
  },
  {
    _id: 422,
    thana_name: "Nakla",
    district: "Sherpur",
    district_code: 89,
  },
  {
    _id: 423,
    thana_name: "Nalitabari",
    district: "Sherpur",
    district_code: 89,
  },
  {
    _id: 424,
    thana_name: "Sherpur Sadar",
    district: "Sherpur",
    district_code: 89,
  },
  {
    _id: 425,
    thana_name: "Sreebardi",
    district: "Sherpur",
    district_code: 89,
  },
  {
    _id: 426,
    thana_name: "Bogra Sadar",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 427,
    thana_name: "Dhunat",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 428,
    thana_name: "Dhupchanchia",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 429,
    thana_name: "Gabtali",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 430,
    thana_name: "Kahaloo",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 431,
    thana_name: "Adamdighi",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 432,
    thana_name: "Nandigram",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 433,
    thana_name: "Sariakandi",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 434,
    thana_name: "Shajahanpur",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 435,
    thana_name: "Sherpur",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 436,
    thana_name: "Shibganj",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 437,
    thana_name: "Sonatola",
    district: "Bogra",
    district_code: 10,
  },
  {
    _id: 438,
    thana_name: "Akkelpur",
    district: "Joypurhat",
    district_code: 38,
  },
  {
    _id: 439,
    thana_name: "Joypurhat Sadar",
    district: "Joypurhat",
    district_code: 38,
  },
  {
    _id: 440,
    thana_name: "Kalai",
    district: "Joypurhat",
    district_code: 38,
  },
  {
    _id: 441,
    thana_name: "Khetlal",
    district: "Joypurhat",
    district_code: 38,
  },
  {
    _id: 442,
    thana_name: "Panchbibi",
    district: "Joypurhat",
    district_code: 38,
  },
  {
    _id: 443,
    thana_name: "Dhamoirhat",
    district: "Naogaon",
    district_code: 64,
  },
  {
    _id: 444,
    thana_name: "Atrai",
    district: "Naogaon",
    district_code: 64,
  },
  {
    _id: 445,
    thana_name: "Manda",
    district: "Naogaon",
    district_code: 64,
  },
  {
    _id: 446,
    thana_name: "Mahadebpur",
    district: "Naogaon",
    district_code: 64,
  },
  {
    _id: 447,
    thana_name: "Badalgachhi",
    district: "Naogaon",
    district_code: 64,
  },
  {
    _id: 448,
    thana_name: "Naogaon Sadar",
    district: "Naogaon",
    district_code: 64,
  },
  {
    _id: 449,
    thana_name: "Niamatpur",
    district: "Naogaon",
    district_code: 64,
  },
  {
    _id: 450,
    thana_name: "Patnitala",
    district: "Naogaon",
    district_code: 64,
  },
  {
    _id: 451,
    thana_name: "Porsha",
    district: "Naogaon",
    district_code: 64,
  },
  {
    _id: 452,
    thana_name: "Raninagar",
    district: "Naogaon",
    district_code: 64,
  },
  {
    _id: 453,
    thana_name: "Sapahar",
    district: "Naogaon",
    district_code: 64,
  },
  {
    _id: 454,
    thana_name: "Baraigram",
    district: "Natore",
    district_code: 69,
  },
  {
    _id: 455,
    thana_name: "Gurudaspur",
    district: "Natore",
    district_code: 69,
  },
  {
    _id: 456,
    thana_name: "Lalpur",
    district: "Natore",
    district_code: 69,
  },
  {
    _id: 457,
    thana_name: "Natore Sadar",
    district: "Natore",
    district_code: 69,
  },
  {
    _id: 458,
    thana_name: "Baghatipara",
    district: "Natore",
    district_code: 69,
  },
  {
    _id: 459,
    thana_name: "Singra",
    district: "Natore",
    district_code: 69,
  },
  {
    _id: 460,
    thana_name: "Naldanga",
    district: "Natore",
    district_code: 69,
  },
  {
    _id: 461,
    thana_name: "Bholahat",
    district: "C. Nababganj",
  },
  {
    _id: 462,
    thana_name: "Gomastapur",
    district: "C. Nababganj",
  },
  {
    _id: 463,
    thana_name: "Nachole",
    district: "C. Nababganj",
  },
  {
    _id: 464,
    thana_name: "Chapai Nababganj Sadar",
    district: "C. Nababganj",
  },
  {
    _id: 465,
    thana_name: "Shibganj",
    district: "C. Nababganj",
  },
  {
    _id: 466,
    thana_name: "Pabna Sadar",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 467,
    thana_name: "Bera",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 468,
    thana_name: "Bhangura",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 469,
    thana_name: "Chatmohar",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 470,
    thana_name: "Faridpur",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 471,
    thana_name: "Ishwardi",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 472,
    thana_name: "Atgharia",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 473,
    thana_name: "Santhia",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 474,
    thana_name: "Sujanagar",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 475,
    thana_name: "Ataikula",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 476,
    thana_name: "Aminpur",
    district: "Pabna",
    district_code: 76,
  },
  {
    _id: 477,
    thana_name: "Karnahar",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 478,
    thana_name: "Damkura",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 479,
    thana_name: "Shah Makhdum",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 480,
    thana_name: "Chandrima",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 481,
    thana_name: "Kasiadanga",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 482,
    thana_name: "Katakhali",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 483,
    thana_name: "Belpukur",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 484,
    thana_name: "Airport",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 485,
    thana_name: "Bagha",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 486,
    thana_name: "Baghmara",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 487,
    thana_name: "Boalia",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 488,
    thana_name: "Charghat",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 489,
    thana_name: "Durgapur",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 490,
    thana_name: "Godagari",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 491,
    thana_name: "Matihar",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 492,
    thana_name: "Mohanpur",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 493,
    thana_name: "Paba",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 494,
    thana_name: "Puthia",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 495,
    thana_name: "Rajpara",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 496,
    thana_name: "Tanore",
    district: "Rajshahi",
    district_code: 81,
  },
  {
    _id: 497,
    thana_name: "Sirajganj Sadar",
    district: "Sirajganj",
    district_code: 88,
  },
  {
    _id: 498,
    thana_name: "Belkuchi",
    district: "Sirajganj",
    district_code: 88,
  },
  {
    _id: 499,
    thana_name: "Chauhali",
    district: "Sirajganj",
    district_code: 88,
  },
  {
    _id: 500,
    thana_name: "Kamarkhanda",
    district: "Sirajganj",
    district_code: 88,
  },
  {
    _id: 501,
    thana_name: "Kazipur",
    district: "Sirajganj",
    district_code: 88,
  },
  {
    _id: 502,
    thana_name: "Roigonj",
    district: "Sirajganj",
    district_code: 88,
  },
  {
    _id: 503,
    thana_name: "Shahjadpur",
    district: "Sirajganj",
    district_code: 88,
  },
  {
    _id: 504,
    thana_name: "Tarash",
    district: "Sirajganj",
    district_code: 88,
  },
  {
    _id: 505,
    thana_name: "UllaPara",
    district: "Sirajganj",
    district_code: 88,
  },
  {
    _id: 506,
    thana_name: "Salanga",
    district: "Sirajganj",
    district_code: 88,
  },
  {
    _id: 507,
    thana_name: "BB. Bridge (West)",
    district: "Sirajganj",
    district_code: 88,
  },
  {
    _id: 508,
    thana_name: "Birampur",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 509,
    thana_name: "Birganj",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 510,
    thana_name: "Biral",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 511,
    thana_name: "Bochaganj",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 512,
    thana_name: "Chirirbandar",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 513,
    thana_name: "Fulbari",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 514,
    thana_name: "Ghoraghat",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 515,
    thana_name: "Hakimpur",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 516,
    thana_name: "Kaharole",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 517,
    thana_name: "Khansama",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 518,
    thana_name: "Dinajpur Sadar",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 519,
    thana_name: "Nawabganj",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 520,
    thana_name: "Parbatipur",
    district: "Dinajpur",
    district_code: 27,
  },
  {
    _id: 521,
    thana_name: "Fulchhari",
    district: "Gaibandha",
    district_code: 32,
  },
  {
    _id: 522,
    thana_name: "Gaibandha Sadar",
    district: "Gaibandha",
    district_code: 32,
  },
  {
    _id: 523,
    thana_name: "Gobindaganj",
    district: "Gaibandha",
    district_code: 32,
  },
  {
    _id: 524,
    thana_name: "Palashbari",
    district: "Gaibandha",
    district_code: 32,
  },
  {
    _id: 525,
    thana_name: "Sadullapur",
    district: "Gaibandha",
    district_code: 32,
  },
  {
    _id: 526,
    thana_name: "Saghata",
    district: "Gaibandha",
    district_code: 32,
  },
  {
    _id: 527,
    thana_name: "Sundarganj",
    district: "Gaibandha",
    district_code: 32,
  },
  {
    _id: 528,
    thana_name: "Phulbari",
    district: "Kurigram",
    district_code: 49,
  },
  {
    _id: 529,
    thana_name: "Kurigram Sadar",
    district: "Kurigram",
    district_code: 49,
  },
  {
    _id: 530,
    thana_name: "Bhurungamari",
    district: "Kurigram",
    district_code: 49,
  },
  {
    _id: 531,
    thana_name: "Nageshwari",
    district: "Kurigram",
    district_code: 49,
  },
  {
    _id: 532,
    thana_name: "Rajarhat",
    district: "Kurigram",
    district_code: 49,
  },
  {
    _id: 533,
    thana_name: "Raumari",
    district: "Kurigram",
    district_code: 49,
  },
  {
    _id: 534,
    thana_name: "Char Rajibpur",
    district: "Kurigram",
    district_code: 49,
  },
  {
    _id: 535,
    thana_name: "Chilmari",
    district: "Kurigram",
    district_code: 49,
  },
  {
    _id: 536,
    thana_name: "Ulipur",
    district: "Kurigram",
    district_code: 49,
  },
  {
    _id: 537,
    thana_name: "Aditmari",
    district: "Lalmonirhat",
    district_code: 52,
  },
  {
    _id: 538,
    thana_name: "Hatibandha",
    district: "Lalmonirhat",
    district_code: 52,
  },
  {
    _id: 539,
    thana_name: "Kaliganj",
    district: "Lalmonirhat",
    district_code: 52,
  },
  {
    _id: 540,
    thana_name: "Lalmonirhat Sadar",
    district: "Lalmonirhat",
    district_code: 52,
  },
  {
    _id: 541,
    thana_name: "Patgram",
    district: "Lalmonirhat",
    district_code: 52,
  },
  {
    _id: 542,
    thana_name: "Dimla Upazila",
    district: "Nilphamari",
    district_code: 73,
  },
  {
    _id: 543,
    thana_name: "Domar Upazila",
    district: "Nilphamari",
    district_code: 73,
  },
  {
    _id: 544,
    thana_name: "Jaldhaka Upazila",
    district: "Nilphamari",
    district_code: 73,
  },
  {
    _id: 545,
    thana_name: "Kishoreganj Upazila",
    district: "Nilphamari",
    district_code: 73,
  },
  {
    _id: 546,
    thana_name: "Nilphamari Sadar Upaz",
    district: "Nilphamari",
    district_code: 73,
  },
  {
    _id: 547,
    thana_name: "Saidpur Upazila",
    district: "Nilphamari",
    district_code: 73,
  },
  {
    _id: 548,
    thana_name: "Boda",
    district: "Panchagarh",
    district_code: 77,
  },
  {
    _id: 549,
    thana_name: "Debiganj",
    district: "Panchagarh",
    district_code: 77,
  },
  {
    _id: 550,
    thana_name: "Atwari",
    district: "Panchagarh",
    district_code: 77,
  },
  {
    _id: 551,
    thana_name: "Panchagarh Sadar",
    district: "Panchagarh",
    district_code: 77,
  },
  {
    _id: 552,
    thana_name: "Tentulia",
    district: "Panchagarh",
    district_code: 77,
  },
  {
    _id: 553,
    thana_name: "Sadar (Kotwali)",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 554,
    thana_name: "Parshuram",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 555,
    thana_name: "Haragach",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 556,
    thana_name: "Tajhat",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 557,
    thana_name: "Mahiganj",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 558,
    thana_name: "Hajirhat",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 559,
    thana_name: "Gangachara",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 560,
    thana_name: "Badarganj",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 561,
    thana_name: "Kaunia",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 562,
    thana_name: "Mitha Pukur",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 563,
    thana_name: "Pirgachha",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 564,
    thana_name: "Pirganj",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 565,
    thana_name: "Taraganj",
    district: "Rangpur",
    district_code: 85,
  },
  {
    _id: 566,
    thana_name: "Haripur",
    district: "Thakurgaon",
    district_code: 94,
  },
  {
    _id: 567,
    thana_name: "Baliadangi",
    district: "Thakurgaon",
    district_code: 94,
  },
  {
    _id: 568,
    thana_name: "Pirganj",
    district: "Thakurgaon",
    district_code: 94,
  },
  {
    _id: 569,
    thana_name: "Ranisankail",
    district: "Thakurgaon",
    district_code: 94,
  },
  {
    _id: 570,
    thana_name: "Thakurgaon Sadar",
    district: "Thakurgaon",
    district_code: 94,
  },
  {
    _id: 571,
    thana_name: "Baniachong",
    district: "Habiganj",
    district_code: 36,
  },
  {
    _id: 572,
    thana_name: "Ajmiriganj",
    district: "Habiganj",
    district_code: 36,
  },
  {
    _id: 573,
    thana_name: "Chunarughat",
    district: "Habiganj",
    district_code: 36,
  },
  {
    _id: 574,
    thana_name: "Habiganj Sadar",
    district: "Habiganj",
    district_code: 36,
  },
  {
    _id: 575,
    thana_name: "Bahubal",
    district: "Habiganj",
    district_code: 36,
  },
  {
    _id: 576,
    thana_name: "Lakhai",
    district: "Habiganj",
    district_code: 36,
  },
  {
    _id: 577,
    thana_name: "Madhabpur",
    district: "Habiganj",
    district_code: 36,
  },
  {
    _id: 578,
    thana_name: "Nabiganj",
    district: "Habiganj",
    district_code: 36,
  },
  {
    _id: 579,
    thana_name: "Barlekha",
    district: "Maulvibazar",
    district_code: 58,
  },
  {
    _id: 580,
    thana_name: "Juri",
    district: "Maulvibazar",
    district_code: 58,
  },
  {
    _id: 581,
    thana_name: "Kamalganj",
    district: "Maulvibazar",
    district_code: 58,
  },
  {
    _id: 582,
    thana_name: "Kulaura",
    district: "Maulvibazar",
    district_code: 58,
  },
  {
    _id: 583,
    thana_name: "Maulvibazar Sadar",
    district: "Maulvibazar",
    district_code: 58,
  },
  {
    _id: 584,
    thana_name: "Rajnagar",
    district: "Maulvibazar",
    district_code: 58,
  },
  {
    _id: 585,
    thana_name: "Sreemangal",
    district: "Maulvibazar",
    district_code: 58,
  },
  {
    _id: 586,
    thana_name: "Bishwambarpur",
    district: "Sunamganj",
    district_code: 90,
  },
  {
    _id: 587,
    thana_name: "Chhatak",
    district: "Sunamganj",
    district_code: 90,
  },
  {
    _id: 588,
    thana_name: "Dakshin Sunamganj",
    district: "Sunamganj",
    district_code: 90,
  },
  {
    _id: 589,
    thana_name: "Derai",
    district: "Sunamganj",
    district_code: 90,
  },
  {
    _id: 590,
    thana_name: "Dharampasha",
    district: "Sunamganj",
    district_code: 90,
  },
  {
    _id: 591,
    thana_name: "Dowarabazar",
    district: "Sunamganj",
    district_code: 90,
  },
  {
    _id: 592,
    thana_name: "Jagannathpur",
    district: "Sunamganj",
    district_code: 90,
  },
  {
    _id: 593,
    thana_name: "Jamalganj",
    district: "Sunamganj",
    district_code: 90,
  },
  {
    _id: 594,
    thana_name: "Sulla",
    district: "Sunamganj",
    district_code: 90,
  },
  {
    _id: 595,
    thana_name: "Sunamganj Sadar",
    district: "Sunamganj",
    district_code: 90,
  },
  {
    _id: 596,
    thana_name: "Tahirpur",
    district: "Sunamganj",
    district_code: 90,
  },
  {
    _id: 597,
    thana_name: "Sylhet (Sadar)",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 598,
    thana_name: "Jalalabad",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 599,
    thana_name: "Airport (Sylhet)",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 600,
    thana_name: "Moglabazar",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 601,
    thana_name: "South Surma",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 602,
    thana_name: "Shah Paran",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 603,
    thana_name: "Beani Bazar",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 604,
    thana_name: "Bishwanath",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 605,
    thana_name: "Companiganj",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 606,
    thana_name: "Dakshin Surma",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 607,
    thana_name: "Fenchuganj",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 608,
    thana_name: "Golapganj",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 609,
    thana_name: "Gowainghat",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 610,
    thana_name: "Jaintiapur",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 611,
    thana_name: "Kanaighat",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 612,
    thana_name: "Balaganj",
    district: "Sylhet",
    district_code: 91,
  },
  {
    _id: 613,
    thana_name: "Zakiganj",
    district: "Sylhet",
    district_code: 91,
  },
];
